version: 2.1
orbs:
  # orgs contain basc recipes and reproducible actions (install node, aws, etc.)
  node: circleci/node@5.0.2
  aws-cli: circleci/aws-cli@1.3.1
  eb: circleci/aws-elastic-beanstalk@2.0.1
  # different jobs are calles later in the workflows sections
jobs:
  build-deploy:
    docker:
      # the base image can run most needed actions with orbs
      - image: "cimg/base:stable"
    steps:
      # - node/install
      - node/install:
          node-version: '16.13'
      - checkout
      - aws-cli/setup
      # - run:
      #     # Installing awsebcli to be able to deploy using eb command
      #     name: "Installing awsebcli"
      #     command: |
      #       sudo apt-get update
      #       sudo apt-get install python3-pip python-dev
      #       sudo pip install awsebcli
      - eb/setup
      # install dependencies in both apps
      - run:
          name: Front-End Install
          command: |
            npm run frontend:install
      - run:
          name: Back-End Install
          command: |
            npm run backend:install
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      - run:
          name: Back-End Build
          command: |
            npm run backend:build
      - run:
          name: Back-End Test
          command: |
            npm run backend:test
      - run:
          name: Front-End Test
          command: |
            npm run frontend:test
      - run:
          name: Deploy Back-end App
          command: |
            npm run backend:deploy
      - run:
          name: Deploy Front-end App
          command: |
            npm run frontend:deploy
      
workflows:
  build-deploy-workflow:
    jobs:
      - build-deploy:
        filters:
          branches:
            only:
              - master 
# Reference of old/not used orbs:
  # node: circleci/node@4.1.0
  # eb: circleci/aws-elastic-beanstalk@1.0.0
  # aws-s3: circleci/aws-s3@3.0.0
